// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AcademyDocumentDataSlicesSlice =
  | NumericListSlice
  | BlogTextTitleSlice
  | BlogSubtitleSlice
  | BlogTextSlice
  | BlogWrappedTextSlice
  | BlogImgSlice;

/**
 * Content for academy documents
 */
interface AcademyDocumentData {
  /**
   * title field in *academy*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: academy.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *academy*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: academy.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * article_link_img field in *academy*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: academy.article_link_img
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  article_link_img: prismic.ImageField<never>;

  /**
   * read_time field in *academy*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: academy.read_time
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  read_time: prismic.RichTextField;

  /**
   * author field in *academy*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: academy.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  author: prismic.RichTextField;

  /**
   * type_name field in *academy*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: academy.type_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type_name: prismic.SelectField<
    'AirDAO products guides' | 'Analytics' | 'Web3 guides'
  >;

  /**
   * badge_type field in *academy*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: academy.badge_type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  badge_type: prismic.SelectField<'Beginner' | 'Intermediate' | 'Pro'>;

  /**
   * Slice Zone field in *academy*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: academy.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AcademyDocumentDataSlicesSlice> /**
   * Meta Description field in *academy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: academy.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *academy*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: academy.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *academy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: academy.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * academy document from Prismic
 *
 * - **API ID**: `academy`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AcademyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<AcademyDocumentData>,
    'academy',
    Lang
  >;

export type AllDocumentTypes = AcademyDocument;

/**
 * Primary content in *BlogImg → Primary*
 */
export interface BlogImgSliceDefaultPrimary {
  /**
   * image field in *BlogImg → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_img.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for BlogImg Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogImgSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<BlogImgSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogImg*
 */
type BlogImgSliceVariation = BlogImgSliceDefault;

/**
 * BlogImg Shared Slice
 *
 * - **API ID**: `blog_img`
 * - **Description**: BlogImg
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogImgSlice = prismic.SharedSlice<
  'blog_img',
  BlogImgSliceVariation
>;

/**
 * Primary content in *BlogSubtitle → Primary*
 */
export interface BlogSubtitleSliceDefaultPrimary {
  /**
   * blog_subtitle_text field in *BlogSubtitle → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_subtitle.primary.blog_subtitle_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  blog_subtitle_text: prismic.RichTextField;
}

/**
 * Default variation for BlogSubtitle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogSubtitleSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<BlogSubtitleSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogSubtitle*
 */
type BlogSubtitleSliceVariation = BlogSubtitleSliceDefault;

/**
 * BlogSubtitle Shared Slice
 *
 * - **API ID**: `blog_subtitle`
 * - **Description**: BlogSubtitle
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogSubtitleSlice = prismic.SharedSlice<
  'blog_subtitle',
  BlogSubtitleSliceVariation
>;

/**
 * Primary content in *BlogText → Primary*
 */
export interface BlogTextSliceDefaultPrimary {
  /**
   * text field in *BlogText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_text.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for BlogText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogTextSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<BlogTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogText*
 */
type BlogTextSliceVariation = BlogTextSliceDefault;

/**
 * BlogText Shared Slice
 *
 * - **API ID**: `blog_text`
 * - **Description**: BlogText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogTextSlice = prismic.SharedSlice<
  'blog_text',
  BlogTextSliceVariation
>;

/**
 * Primary content in *BlogTextTitle → Primary*
 */
export interface BlogTextTitleSliceDefaultPrimary {
  /**
   * Title field in *BlogTextTitle → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title
   * - **API ID Path**: blog_text_title.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;
}

/**
 * Default variation for BlogTextTitle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogTextTitleSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<BlogTextTitleSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogTextTitle*
 */
type BlogTextTitleSliceVariation = BlogTextTitleSliceDefault;

/**
 * BlogTextTitle Shared Slice
 *
 * - **API ID**: `blog_text_title`
 * - **Description**: BlogTextTitle
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogTextTitleSlice = prismic.SharedSlice<
  'blog_text_title',
  BlogTextTitleSliceVariation
>;

/**
 * Primary content in *BlogWrappedText → Primary*
 */
export interface BlogWrappedTextSliceDefaultPrimary {
  /**
   * blog_wrapped_text field in *BlogWrappedText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_wrapped_text.primary.blog_wrapped_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  blog_wrapped_text: prismic.RichTextField;
}

/**
 * Default variation for BlogWrappedText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogWrappedTextSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<BlogWrappedTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogWrappedText*
 */
type BlogWrappedTextSliceVariation = BlogWrappedTextSliceDefault;

/**
 * BlogWrappedText Shared Slice
 *
 * - **API ID**: `blog_wrapped_text`
 * - **Description**: BlogWrappedText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogWrappedTextSlice = prismic.SharedSlice<
  'blog_wrapped_text',
  BlogWrappedTextSliceVariation
>;

/**
 * Primary content in *CexCard → Primary*
 */
export interface CexCardSliceDefaultPrimary {
  /**
   * name field in *CexCard → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: name
   * - **API ID Path**: cex_card.primary.name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * icon field in *CexCard → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cex_card.primary.icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Primary content in *CexCard → Items*
 */
export interface CexCardSliceDefaultItem {
  /**
   * pair name field in *CexCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cex_card.items[].pair_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pair_name: prismic.KeyTextField;

  /**
   * pair link field in *CexCard → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cex_card.items[].pair_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  pair_link: prismic.LinkField;
}

/**
 * Default variation for CexCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CexCardSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<CexCardSliceDefaultPrimary>,
  Simplify<CexCardSliceDefaultItem>
>;

/**
 * Slice variation for *CexCard*
 */
type CexCardSliceVariation = CexCardSliceDefault;

/**
 * CexCard Shared Slice
 *
 * - **API ID**: `cex_card`
 * - **Description**: CexCard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CexCardSlice = prismic.SharedSlice<
  'cex_card',
  CexCardSliceVariation
>;

/**
 * Primary content in *FooterContact → Primary*
 */
export interface FooterContactSliceDefaultPrimary {
  /**
   * test field in *FooterContact → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_contact.primary.test
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  test: prismic.RichTextField;
}

/**
 * Default variation for FooterContact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterContactSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FooterContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FooterContact*
 */
type FooterContactSliceVariation = FooterContactSliceDefault;

/**
 * FooterContact Shared Slice
 *
 * - **API ID**: `footer_contact`
 * - **Description**: FooterContact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterContactSlice = prismic.SharedSlice<
  'footer_contact',
  FooterContactSliceVariation
>;

/**
 * Primary content in *FooterEvents → Primary*
 */
export interface FooterEventsSliceDefaultPrimary {
  /**
   * test field in *FooterEvents → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_events.primary.test
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  test: prismic.RichTextField;
}

/**
 * Default variation for FooterEvents Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterEventsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FooterEventsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FooterEvents*
 */
type FooterEventsSliceVariation = FooterEventsSliceDefault;

/**
 * FooterEvents Shared Slice
 *
 * - **API ID**: `footer_events`
 * - **Description**: FooterEvents
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterEventsSlice = prismic.SharedSlice<
  'footer_events',
  FooterEventsSliceVariation
>;

/**
 * Primary content in *FooterItem → Items*
 */
export interface FooterItemSliceDefaultItem {
  /**
   * footer_item_text field in *FooterItem → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_item.items[].footer_item_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  footer_item_text: prismic.RichTextField;

  /**
   * footer_item_url field in *FooterItem → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_item.items[].footer_item_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  footer_item_url: prismic.LinkField;

  /**
   * footer_item_is_title field in *FooterItem → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: footer_item.items[].footer_item_is_title
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  footer_item_is_title: prismic.BooleanField;

  /**
   * footer_item_is_soon field in *FooterItem → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: footer_item.items[].footer_item_is_soon
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  footer_item_is_soon: prismic.BooleanField;
}

/**
 * Default variation for FooterItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterItemSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  Simplify<FooterItemSliceDefaultItem>
>;

/**
 * Slice variation for *FooterItem*
 */
type FooterItemSliceVariation = FooterItemSliceDefault;

/**
 * FooterItem Shared Slice
 *
 * - **API ID**: `footer_item`
 * - **Description**: FooterItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterItemSlice = prismic.SharedSlice<
  'footer_item',
  FooterItemSliceVariation
>;

/**
 * Primary content in *NavItem → Primary*
 */
export interface NavItemSliceDefaultPrimary {
  /**
   * navLabel field in *NavItem → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_item.primary.navlabel
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  navlabel: prismic.RichTextField;
}

/**
 * Primary content in *NavItem → Items*
 */
export interface NavItemSliceDefaultItem {
  /**
   * navItemImg field in *NavItem → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_item.items[].navitemimg
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  navitemimg: prismic.ImageField<never>;

  /**
   * navItemLabel field in *NavItem → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_item.items[].navitemlabel
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  navitemlabel: prismic.RichTextField;

  /**
   * navItemDescr field in *NavItem → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_item.items[].navitemdescr
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  navitemdescr: prismic.RichTextField;

  /**
   * navItemUrl field in *NavItem → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_item.items[].navitemurl
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  navitemurl: prismic.RichTextField;

  /**
   * navItemLink field in *NavItem → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_item.items[].navitemlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  navitemlink: prismic.LinkField;
}

/**
 * Default variation for NavItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavItemSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<NavItemSliceDefaultPrimary>,
  Simplify<NavItemSliceDefaultItem>
>;

/**
 * Slice variation for *NavItem*
 */
type NavItemSliceVariation = NavItemSliceDefault;

/**
 * NavItem Shared Slice
 *
 * - **API ID**: `nav_item`
 * - **Description**: NavItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavItemSlice = prismic.SharedSlice<
  'nav_item',
  NavItemSliceVariation
>;

/**
 * Primary content in *NumericList → Items*
 */
export interface NumericListSliceDefaultItem {
  /**
   * number field in *NumericList → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: numeric_list.items[].number
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  number: prismic.RichTextField;

  /**
   * text field in *NumericList → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: numeric_list.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for NumericList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NumericListSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  Simplify<NumericListSliceDefaultItem>
>;

/**
 * Slice variation for *NumericList*
 */
type NumericListSliceVariation = NumericListSliceDefault;

/**
 * NumericList Shared Slice
 *
 * - **API ID**: `numeric_list`
 * - **Description**: NumericList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NumericListSlice = prismic.SharedSlice<
  'numeric_list',
  NumericListSliceVariation
>;

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AcademyDocument,
      AcademyDocumentData,
      AcademyDocumentDataSlicesSlice,
      AllDocumentTypes,
      BlogImgSlice,
      BlogImgSliceDefaultPrimary,
      BlogImgSliceVariation,
      BlogImgSliceDefault,
      BlogSubtitleSlice,
      BlogSubtitleSliceDefaultPrimary,
      BlogSubtitleSliceVariation,
      BlogSubtitleSliceDefault,
      BlogTextSlice,
      BlogTextSliceDefaultPrimary,
      BlogTextSliceVariation,
      BlogTextSliceDefault,
      BlogTextTitleSlice,
      BlogTextTitleSliceDefaultPrimary,
      BlogTextTitleSliceVariation,
      BlogTextTitleSliceDefault,
      BlogWrappedTextSlice,
      BlogWrappedTextSliceDefaultPrimary,
      BlogWrappedTextSliceVariation,
      BlogWrappedTextSliceDefault,
      CexCardSlice,
      CexCardSliceDefaultPrimary,
      CexCardSliceDefaultItem,
      CexCardSliceVariation,
      CexCardSliceDefault,
      FooterContactSlice,
      FooterContactSliceDefaultPrimary,
      FooterContactSliceVariation,
      FooterContactSliceDefault,
      FooterEventsSlice,
      FooterEventsSliceDefaultPrimary,
      FooterEventsSliceVariation,
      FooterEventsSliceDefault,
      FooterItemSlice,
      FooterItemSliceDefaultItem,
      FooterItemSliceVariation,
      FooterItemSliceDefault,
      NavItemSlice,
      NavItemSliceDefaultPrimary,
      NavItemSliceDefaultItem,
      NavItemSliceVariation,
      NavItemSliceDefault,
      NumericListSlice,
      NumericListSliceDefaultItem,
      NumericListSliceVariation,
      NumericListSliceDefault,
    };
  }
}
