// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog_img: dynamic(() => import("./BlogImg")),
  blog_subtitle: dynamic(() => import("./BlogSubtitle")),
  blog_text: dynamic(() => import("./BlogText")),
  blog_wrapped_text: dynamic(() => import("./BlogWrappedText")),
  cex_card: dynamic(() => import("./CexCard")),
  footer_contact: dynamic(() => import("./FooterContact")),
  footer_events: dynamic(() => import("./FooterEvents")),
  footer_item: dynamic(() => import("./FooterItem")),
  nav_item: dynamic(() => import("./NavItem")),
  roadmap_post: dynamic(() => import("./RoadmapPost")),
};
